#!/usr/bin/env python3
"""Generate studio inventory data files from the Unicode Character Database.

Emits web/data/glyphs-extended-ab.js: Myanmar Extended-A (U+AA60–AA7F,
Khamti Shan, Aiton, Pa'O) and Extended-B (U+A9E0–A9FF, Tai Laing and
Shan Pali) glyph records, the same record shape as glyphs-extended.js.

Names are uniXXXX production names, so pipeline/json_to_ufo.py resolves
codepoints and mark classification without any per-character tables.
Regenerate rather than hand-editing the output:

    python3 pipeline/gen_inventory.py web/data/glyphs-extended-ab.js

Myanmar Extended-C (U+116D0–116FF, Unicode 16) is intentionally NOT
emitted yet: this Python's unicodedata predates it and no common guide
font covers it. The pipeline already accepts its uXXXXX names.
"""

import json
import sys
import unicodedata
from pathlib import Path

BLOCKS = [
    {
        "range": (0xA9E0, 0xA9FF),
        "group": "extB",
        "en": "Tai Laing · Shan Pali (Ext-B)",
        "my": "တိုင်းလိုင် · ရှမ်းပါဠိ",
        "hint_my": "တိုင်းလိုင် အက္ခရာ",
    },
    {
        "range": (0xAA60, 0xAA7F),
        "group": "extA",
        "en": "Khamti Shan · Aiton (Ext-A)",
        "my": "ခန္တီးရှမ်း · အိုက်တွန်",
        "hint_my": "ခန္တီးရှမ်း အက္ခရာ",
    },
]

MARK_SUFFIX_EN = " — draw only the mark"
MARK_SUFFIX_MY = " — သင်္ကေတကိုသာ ဆွဲပါ"
DOTTED = "◌"


def short_name(cp):
    """UCD name minus the script prefix, in the inventory's Title Case."""
    full = unicodedata.name(chr(cp))
    words = full.removeprefix("MYANMAR ").split()
    return " ".join(w.capitalize() for w in words)


def record(cp, block):
    ch = chr(cp)
    cat = unicodedata.category(ch)
    is_mn = cat == "Mn"
    display = (DOTTED + ch) if cat in ("Mn", "Mc") else ch
    hint = short_name(cp) + (MARK_SUFFIX_EN if is_mn else "")
    hint_my = block["hint_my"] + (MARK_SUFFIX_MY if is_mn else "")
    return {
        "name": f"uni{cp:04X}",
        "cp": cp,
        "label": display,
        "guide": display,
        "hint": hint,
        "hintMy": hint_my,
        "mark": is_mn,
        "group": block["group"],
    }


def js_record(r):
    parts = [
        f'name:{json.dumps(r["name"])}',
        f'cp:0x{r["cp"]:04X}',
        f'label:{json.dumps(r["label"], ensure_ascii=False)}',
        f'guide:{json.dumps(r["guide"], ensure_ascii=False)}',
        f'hint:{json.dumps(r["hint"], ensure_ascii=False)}',
        f'hintMy:{json.dumps(r["hintMy"], ensure_ascii=False)}',
        f'mark:{"true" if r["mark"] else "false"}',
        f'group:{json.dumps(r["group"])}',
    ]
    return "    {" + ", ".join(parts) + "},"


def main():
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else (
        Path(__file__).resolve().parent.parent
        / "web" / "data" / "glyphs-extended-ab.js")

    records, skipped = [], 0
    for block in BLOCKS:
        lo, hi = block["range"]
        for cp in range(lo, hi + 1):
            try:
                unicodedata.name(chr(cp))
            except ValueError:
                skipped += 1
                continue
            records.append(record(cp, block))

    groups = ",\n".join(
        f'    {{ key: {json.dumps(b["group"])}, '
        f'en: {json.dumps(b["en"], ensure_ascii=False)}, '
        f'my: {json.dumps(b["my"], ensure_ascii=False)} }}'
        for b in BLOCKS)

    body = "\n".join(js_record(r) for r in records)
    out = f"""/*
 * Myanmar Extended-A (U+AA60–AA7F: Khamti Shan, Aiton, Pa'O) and
 * Extended-B (U+A9E0–A9FF: Tai Laing, Shan Pali) coverage.
 *
 * GENERATED by pipeline/gen_inventory.py from the Unicode Character
 * Database — regenerate rather than hand-editing. Guides need a font
 * covering these blocks (Padauk or Noto Sans Myanmar).
 */
(function () {{
  "use strict";
  var G = [
{body}
  ];
  window.GLYPH_GROUPS.push(
{groups}
  );
  G.forEach(function (g) {{ window.GLYPHS.push(g); window.GLYPH_BY_NAME[g.name] = g; }});
}})();
"""
    out_path.write_text(out, encoding="utf-8")
    print(f"Wrote {out_path}: {len(records)} glyph records"
          + (f" ({skipped} unassigned codepoints skipped)" if skipped else ""))


if __name__ == "__main__":
    main()
