#!/usr/bin/env python3
"""Fetch a freely-licensed Burmese book and page it for web/book.html.

A proof sheet shows a font its best case: the clusters someone chose to
put on it. A book shows it the case nobody chose — thousands of words in
a row, set at reading size, where a mark two units out of place stops
being a measurement and starts being a thing you notice on page nine.

The default text is ကဗျာသာရတ္ထသတ်ပုံ, a classical Burmese orthography
primer in verse by ညောင်ကန်ဆရာတော် — a spelling book. It is the most
demanding proof text I could find and the most appropriate one: page
after page of words grouped by the very medials, stacks and tone marks
that a Myanmar font gets wrong, chosen by its author precisely because
they are the hard ones to spell.

    python3 make_book.py                        # -> ../web/data/book.js
    python3 make_book.py --title 'ကဏှဒီပါယနဇာတ်'
    python3 make_book.py --chars-per-page 1200

Licensing. The text comes from မြန်မာဝီကီရင်းမြစ် (Burmese Wikisource),
where contributor transcriptions are CC BY-SA 4.0; the underlying work is
a classical one. The output file carries that attribution in its own
header and is kept out of the MIT-licensed sources for the same reason
web/data/vocabulary.js is.

Dependencies: none beyond the standard library.
"""

import argparse
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from repo_paths import repo_root  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "web" / "data" / "book.js"
API = "https://my.wikisource.org/w/api.php"
UA = ("myanmar-glyph-studio/0.4 (font rendering test; "
      "https://github.com/Thiha-Lynn/myanmar-glyph-studio)")

DEFAULT_TITLE = "ကဗျာသာရတ္ထသတ်ပုံ"
DEFAULT_AUTHOR = "ညောင်ကန်ဆရာတော်"
DEFAULT_BLURB = (
    "ကဗျာသာရတ္ထသတ်ပုံ — a classical Burmese orthography primer in verse. "
    "Its subject is correct spelling, so it is written almost entirely out "
    "of the clusters a Myanmar font finds hardest: medial stacks, tone "
    "marks, subjoined consonants, the ြ wrap in every width. A spelling "
    "book is the fairest possible test of a typeface that claims to spell.")

HEADER = """\
/*
 * A freely-licensed Burmese book, paged for web/book.html.
 *
 * NOT part of this project's MIT-licensed source. Redistributed under the
 * licence of its source, with attribution:
 *
 *   Text: မြန်မာဝီကီရင်းမြစ် (Burmese Wikisource), CC BY-SA 4.0
 *         https://my.wikisource.org/wiki/%(quoted)s
 *   Work: %(title)s — %(author)s (classical)
 *
 * GENERATED by pipeline/make_book.py — regenerate rather than hand-editing.
 */
"""


def fetch(title):
    query = urllib.parse.urlencode({
        "action": "query", "prop": "revisions", "rvprop": "content",
        "rvslots": "main", "titles": title,
        "format": "json", "formatversion": "2"})
    request = urllib.request.Request(f"{API}?{query}", headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            data = json.load(response)
    except urllib.error.URLError as exc:
        sys.exit(f"could not reach Wikisource: {exc}")
    pages = data.get("query", {}).get("pages", [])
    if not pages or "revisions" not in pages[0]:
        sys.exit(f"no such page: {title}")
    return pages[0]["revisions"][0]["slots"]["main"]["content"]


def to_text(wikitext):
    """Wikitext to plain Burmese paragraphs, keeping only the prose."""
    text = re.sub(r"\{\{[^{}]*\}\}", "", wikitext)          # templates
    text = re.sub(r"\{\{.*?\}\}", "", text, flags=re.S)     # nested leftovers
    text = re.sub(r"<ref.*?</ref>", "", text, flags=re.S)
    text = re.sub(r"<[^>]+>", "\n", text)                   # poem/h3/p tags
    text = re.sub(r"\[\[(?:[^\]|]*\|)?([^\]]*)\]\]", r"\1", text)  # links
    text = re.sub(r"'{2,}", "", text)                       # bold/italic
    text = re.sub(r"^[=*#:;]+\s*", "", text, flags=re.M)    # headings, lists
    text = text.replace("&nbsp;", " ")
    lines = [re.sub(r"\s+", " ", line).strip() for line in text.split("\n")]
    return [line for line in lines if len(line) > 1]


def paginate(paragraphs, chars_per_page):
    """Break the prose into pages without splitting a Burmese word.

    Burmese does not put spaces between words, but it does put them
    between phrases, and this text is verse with generous phrase spacing.
    Breaking on those spaces keeps every syllable cluster whole — which
    matters here, because a cluster split across a page break would be a
    rendering artefact of this script rather than of the font.
    """
    pages, current, size = [], [], 0
    for para in paragraphs:
        words = para.split(" ")
        chunk = []
        for word in words:
            chunk.append(word)
            size += len(word) + 1
            if size >= chars_per_page:
                current.append(" ".join(chunk))
                pages.append(current)
                current, chunk, size = [], [], 0
        if chunk:
            current.append(" ".join(chunk))
    if current:
        pages.append(current)
    return pages


def main():
    ap = argparse.ArgumentParser(
        description="Page a Burmese Wikisource book for web/book.html.")
    ap.add_argument("--title", default=DEFAULT_TITLE)
    ap.add_argument("--author", default=DEFAULT_AUTHOR)
    ap.add_argument("--blurb", default=None)
    ap.add_argument("--chars-per-page", type=int, default=820)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    repo_root("mgs-book")   # writes into web/data/ — needs a checkout

    paragraphs = to_text(fetch(args.title))
    pages = paginate(paragraphs, args.chars_per_page)
    chars = sum(len(p) for page in pages for p in page)
    blurb = args.blurb if args.blurb is not None else (
        DEFAULT_BLURB if args.title == DEFAULT_TITLE else "")

    payload = {
        "title": args.title,
        "author": args.author,
        "blurb": blurb,
        "source": "https://my.wikisource.org/wiki/" +
                  urllib.parse.quote(args.title.replace(" ", "_")),
        "licence": "CC BY-SA 4.0",
        "chars": chars,
        "pages": pages,
    }
    header = HEADER % {"title": args.title, "author": args.author,
                       "quoted": urllib.parse.quote(args.title.replace(" ", "_"))}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        header + '(function () {\n  "use strict";\n  window.BOOK = ' +
        json.dumps(payload, ensure_ascii=False) + ";\n}());\n",
        encoding="utf-8")
    print(f"{args.out}: {len(pages)} pages, {chars} characters "
          f"({args.out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
